// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: tasks/epic/epic.proto

package epic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EpicRegistryClient is the client API for EpicRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EpicRegistryClient interface {
	Create(ctx context.Context, in *EpicCreateRequest, opts ...grpc.CallOption) (*EpicCreateResponse, error)
	Update(ctx context.Context, in *EpicUpdateRequest, opts ...grpc.CallOption) (*EpicUpdateResponse, error)
	Get(ctx context.Context, in *EpicGetRequest, opts ...grpc.CallOption) (*EpicGetResponse, error)
	GetByID(ctx context.Context, in *EpicGetByIDRequest, opts ...grpc.CallOption) (*EpicGetByIDResponse, error)
}

type epicRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewEpicRegistryClient(cc grpc.ClientConnInterface) EpicRegistryClient {
	return &epicRegistryClient{cc}
}

func (c *epicRegistryClient) Create(ctx context.Context, in *EpicCreateRequest, opts ...grpc.CallOption) (*EpicCreateResponse, error) {
	out := new(EpicCreateResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.tasks.epic.EpicRegistry/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epicRegistryClient) Update(ctx context.Context, in *EpicUpdateRequest, opts ...grpc.CallOption) (*EpicUpdateResponse, error) {
	out := new(EpicUpdateResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.tasks.epic.EpicRegistry/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epicRegistryClient) Get(ctx context.Context, in *EpicGetRequest, opts ...grpc.CallOption) (*EpicGetResponse, error) {
	out := new(EpicGetResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.tasks.epic.EpicRegistry/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *epicRegistryClient) GetByID(ctx context.Context, in *EpicGetByIDRequest, opts ...grpc.CallOption) (*EpicGetByIDResponse, error) {
	out := new(EpicGetByIDResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.tasks.epic.EpicRegistry/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EpicRegistryServer is the server API for EpicRegistry service.
// All implementations should embed UnimplementedEpicRegistryServer
// for forward compatibility
type EpicRegistryServer interface {
	Create(context.Context, *EpicCreateRequest) (*EpicCreateResponse, error)
	Update(context.Context, *EpicUpdateRequest) (*EpicUpdateResponse, error)
	Get(context.Context, *EpicGetRequest) (*EpicGetResponse, error)
	GetByID(context.Context, *EpicGetByIDRequest) (*EpicGetByIDResponse, error)
}

// UnimplementedEpicRegistryServer should be embedded to have forward compatible implementations.
type UnimplementedEpicRegistryServer struct {
}

func (UnimplementedEpicRegistryServer) Create(context.Context, *EpicCreateRequest) (*EpicCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEpicRegistryServer) Update(context.Context, *EpicUpdateRequest) (*EpicUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedEpicRegistryServer) Get(context.Context, *EpicGetRequest) (*EpicGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEpicRegistryServer) GetByID(context.Context, *EpicGetByIDRequest) (*EpicGetByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}

// UnsafeEpicRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EpicRegistryServer will
// result in compilation errors.
type UnsafeEpicRegistryServer interface {
	mustEmbedUnimplementedEpicRegistryServer()
}

func RegisterEpicRegistryServer(s grpc.ServiceRegistrar, srv EpicRegistryServer) {
	s.RegisterService(&EpicRegistry_ServiceDesc, srv)
}

func _EpicRegistry_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpicCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpicRegistryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.tasks.epic.EpicRegistry/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpicRegistryServer).Create(ctx, req.(*EpicCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpicRegistry_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpicUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpicRegistryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.tasks.epic.EpicRegistry/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpicRegistryServer).Update(ctx, req.(*EpicUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpicRegistry_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpicGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpicRegistryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.tasks.epic.EpicRegistry/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpicRegistryServer).Get(ctx, req.(*EpicGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpicRegistry_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpicGetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpicRegistryServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.tasks.epic.EpicRegistry/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpicRegistryServer).GetByID(ctx, req.(*EpicGetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EpicRegistry_ServiceDesc is the grpc.ServiceDesc for EpicRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EpicRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.constantine27k.crnt_data_manager.api.tasks.epic.EpicRegistry",
	HandlerType: (*EpicRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EpicRegistry_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EpicRegistry_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _EpicRegistry_Get_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _EpicRegistry_GetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tasks/epic/epic.proto",
}
