// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/tasks/subtask/subtask.proto

package subtask

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubtaskRegistryClient is the client API for SubtaskRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubtaskRegistryClient interface {
	Create(ctx context.Context, in *SubtaskCreateRequest, opts ...grpc.CallOption) (*SubtaskCreateResponse, error)
	Update(ctx context.Context, in *SubtaskUpdateRequest, opts ...grpc.CallOption) (*SubtaskUpdateResponse, error)
	Get(ctx context.Context, in *SubtaskGetRequest, opts ...grpc.CallOption) (*SubtaskGetResponse, error)
	GetByID(ctx context.Context, in *SubtaskGetByIDRequest, opts ...grpc.CallOption) (*SubtaskGetByIDResponse, error)
}

type subtaskRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewSubtaskRegistryClient(cc grpc.ClientConnInterface) SubtaskRegistryClient {
	return &subtaskRegistryClient{cc}
}

func (c *subtaskRegistryClient) Create(ctx context.Context, in *SubtaskCreateRequest, opts ...grpc.CallOption) (*SubtaskCreateResponse, error) {
	out := new(SubtaskCreateResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.tasks.subtask.SubtaskRegistry/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subtaskRegistryClient) Update(ctx context.Context, in *SubtaskUpdateRequest, opts ...grpc.CallOption) (*SubtaskUpdateResponse, error) {
	out := new(SubtaskUpdateResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.tasks.subtask.SubtaskRegistry/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subtaskRegistryClient) Get(ctx context.Context, in *SubtaskGetRequest, opts ...grpc.CallOption) (*SubtaskGetResponse, error) {
	out := new(SubtaskGetResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.tasks.subtask.SubtaskRegistry/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subtaskRegistryClient) GetByID(ctx context.Context, in *SubtaskGetByIDRequest, opts ...grpc.CallOption) (*SubtaskGetByIDResponse, error) {
	out := new(SubtaskGetByIDResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.tasks.subtask.SubtaskRegistry/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubtaskRegistryServer is the server API for SubtaskRegistry service.
// All implementations should embed UnimplementedSubtaskRegistryServer
// for forward compatibility
type SubtaskRegistryServer interface {
	Create(context.Context, *SubtaskCreateRequest) (*SubtaskCreateResponse, error)
	Update(context.Context, *SubtaskUpdateRequest) (*SubtaskUpdateResponse, error)
	Get(context.Context, *SubtaskGetRequest) (*SubtaskGetResponse, error)
	GetByID(context.Context, *SubtaskGetByIDRequest) (*SubtaskGetByIDResponse, error)
}

// UnimplementedSubtaskRegistryServer should be embedded to have forward compatible implementations.
type UnimplementedSubtaskRegistryServer struct {
}

func (UnimplementedSubtaskRegistryServer) Create(context.Context, *SubtaskCreateRequest) (*SubtaskCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSubtaskRegistryServer) Update(context.Context, *SubtaskUpdateRequest) (*SubtaskUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSubtaskRegistryServer) Get(context.Context, *SubtaskGetRequest) (*SubtaskGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSubtaskRegistryServer) GetByID(context.Context, *SubtaskGetByIDRequest) (*SubtaskGetByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}

// UnsafeSubtaskRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubtaskRegistryServer will
// result in compilation errors.
type UnsafeSubtaskRegistryServer interface {
	mustEmbedUnimplementedSubtaskRegistryServer()
}

func RegisterSubtaskRegistryServer(s grpc.ServiceRegistrar, srv SubtaskRegistryServer) {
	s.RegisterService(&SubtaskRegistry_ServiceDesc, srv)
}

func _SubtaskRegistry_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubtaskCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtaskRegistryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.tasks.subtask.SubtaskRegistry/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtaskRegistryServer).Create(ctx, req.(*SubtaskCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubtaskRegistry_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubtaskUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtaskRegistryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.tasks.subtask.SubtaskRegistry/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtaskRegistryServer).Update(ctx, req.(*SubtaskUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubtaskRegistry_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubtaskGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtaskRegistryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.tasks.subtask.SubtaskRegistry/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtaskRegistryServer).Get(ctx, req.(*SubtaskGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubtaskRegistry_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubtaskGetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtaskRegistryServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.tasks.subtask.SubtaskRegistry/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtaskRegistryServer).GetByID(ctx, req.(*SubtaskGetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubtaskRegistry_ServiceDesc is the grpc.ServiceDesc for SubtaskRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubtaskRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.constantine27k.crnt_data_manager.api.tasks.subtask.SubtaskRegistry",
	HandlerType: (*SubtaskRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SubtaskRegistry_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SubtaskRegistry_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SubtaskRegistry_Get_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _SubtaskRegistry_GetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tasks/subtask/subtask.proto",
}
