version: '3'
services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=crnt-dm-user
      - POSTGRESQL_PASSWORD=crnt-dm-password
      - POSTGRESQL_DATABASE=crnt-dm-db
    ports:
      - "5432:5432"
    networks:
      - "crnt-data"

  pg-up-checker:
    image: oliosinter/ansible-probe:1.0.0
    environment:
      PROBE_HOST: postgres
      PROBE_PORT: 5432
      PROBE_TIMEOUT: 20
    command: [ "probe.yml" ]
    networks:
      - "crnt-data"

networks:
  crnt-data:
    external: true
