// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/sprint/sprint.proto

package sprint

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SprintRegistryClient is the client API for SprintRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SprintRegistryClient interface {
	CreateSprint(ctx context.Context, in *SprintCreateRequest, opts ...grpc.CallOption) (*SprintCreateResponse, error)
	UpdateSprint(ctx context.Context, in *SprintUpdateRequest, opts ...grpc.CallOption) (*SprintUpdateResponse, error)
	GetSprint(ctx context.Context, in *SprintGetRequest, opts ...grpc.CallOption) (*SprintGetResponse, error)
	GetSprintByID(ctx context.Context, in *SprintGetByIDRequest, opts ...grpc.CallOption) (*SprintGetByIDResponse, error)
}

type sprintRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewSprintRegistryClient(cc grpc.ClientConnInterface) SprintRegistryClient {
	return &sprintRegistryClient{cc}
}

func (c *sprintRegistryClient) CreateSprint(ctx context.Context, in *SprintCreateRequest, opts ...grpc.CallOption) (*SprintCreateResponse, error) {
	out := new(SprintCreateResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.sprint.SprintRegistry/CreateSprint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintRegistryClient) UpdateSprint(ctx context.Context, in *SprintUpdateRequest, opts ...grpc.CallOption) (*SprintUpdateResponse, error) {
	out := new(SprintUpdateResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.sprint.SprintRegistry/UpdateSprint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintRegistryClient) GetSprint(ctx context.Context, in *SprintGetRequest, opts ...grpc.CallOption) (*SprintGetResponse, error) {
	out := new(SprintGetResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.sprint.SprintRegistry/GetSprint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintRegistryClient) GetSprintByID(ctx context.Context, in *SprintGetByIDRequest, opts ...grpc.CallOption) (*SprintGetByIDResponse, error) {
	out := new(SprintGetByIDResponse)
	err := c.cc.Invoke(ctx, "/github.constantine27k.crnt_data_manager.api.sprint.SprintRegistry/GetSprintByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SprintRegistryServer is the server API for SprintRegistry service.
// All implementations should embed UnimplementedSprintRegistryServer
// for forward compatibility
type SprintRegistryServer interface {
	CreateSprint(context.Context, *SprintCreateRequest) (*SprintCreateResponse, error)
	UpdateSprint(context.Context, *SprintUpdateRequest) (*SprintUpdateResponse, error)
	GetSprint(context.Context, *SprintGetRequest) (*SprintGetResponse, error)
	GetSprintByID(context.Context, *SprintGetByIDRequest) (*SprintGetByIDResponse, error)
}

// UnimplementedSprintRegistryServer should be embedded to have forward compatible implementations.
type UnimplementedSprintRegistryServer struct {
}

func (UnimplementedSprintRegistryServer) CreateSprint(context.Context, *SprintCreateRequest) (*SprintCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSprint not implemented")
}
func (UnimplementedSprintRegistryServer) UpdateSprint(context.Context, *SprintUpdateRequest) (*SprintUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSprint not implemented")
}
func (UnimplementedSprintRegistryServer) GetSprint(context.Context, *SprintGetRequest) (*SprintGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSprint not implemented")
}
func (UnimplementedSprintRegistryServer) GetSprintByID(context.Context, *SprintGetByIDRequest) (*SprintGetByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSprintByID not implemented")
}

// UnsafeSprintRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SprintRegistryServer will
// result in compilation errors.
type UnsafeSprintRegistryServer interface {
	mustEmbedUnimplementedSprintRegistryServer()
}

func RegisterSprintRegistryServer(s grpc.ServiceRegistrar, srv SprintRegistryServer) {
	s.RegisterService(&SprintRegistry_ServiceDesc, srv)
}

func _SprintRegistry_CreateSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SprintCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintRegistryServer).CreateSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.sprint.SprintRegistry/CreateSprint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintRegistryServer).CreateSprint(ctx, req.(*SprintCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintRegistry_UpdateSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SprintUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintRegistryServer).UpdateSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.sprint.SprintRegistry/UpdateSprint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintRegistryServer).UpdateSprint(ctx, req.(*SprintUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintRegistry_GetSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SprintGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintRegistryServer).GetSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.sprint.SprintRegistry/GetSprint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintRegistryServer).GetSprint(ctx, req.(*SprintGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintRegistry_GetSprintByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SprintGetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintRegistryServer).GetSprintByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.constantine27k.crnt_data_manager.api.sprint.SprintRegistry/GetSprintByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintRegistryServer).GetSprintByID(ctx, req.(*SprintGetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SprintRegistry_ServiceDesc is the grpc.ServiceDesc for SprintRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SprintRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.constantine27k.crnt_data_manager.api.sprint.SprintRegistry",
	HandlerType: (*SprintRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSprint",
			Handler:    _SprintRegistry_CreateSprint_Handler,
		},
		{
			MethodName: "UpdateSprint",
			Handler:    _SprintRegistry_UpdateSprint_Handler,
		},
		{
			MethodName: "GetSprint",
			Handler:    _SprintRegistry_GetSprint_Handler,
		},
		{
			MethodName: "GetSprintByID",
			Handler:    _SprintRegistry_GetSprintByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/sprint/sprint.proto",
}
